apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "rendered.yaml"

secretGenerator:
  - name: pasteboard-spotify
    namespace: pasteboard
    files:
    - cookie=.spotify-cookie.txt
