apiVersion: v1
kind: Namespace
metadata:
  name: pasteboard
---
apiVersion: v1
kind: Service
metadata:
  name: pasteboard
  namespace: pasteboard
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9999
  selector:
    app: pasteboard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pasteboard-postgres
  namespace: pasteboard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pasteboard
  name: pasteboard
  namespace: pasteboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pasteboard
  template:
    metadata:
      labels:
        app: pasteboard
    spec:
      containers:
      - image: redisfab/rejson:master-arm64v8-bionic
        name: redis
        ports:
        - containerPort: 6379
          name: redis
      - env:
        - name: POSTGRES_USER
          value: spotify
        - name: POSTGRES_PASSWORD
          value: spotify
        - name: POSTGRES_DB
          value: spotify
        image: postgres:14.1
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: pgdata
      - command:
        - yarn
        - node
        - /app/packages/spotify/build/index.js
        env:
        - name: TYPEORM_CONNECTION
          value: postgres
        - name: TYPEORM_HOST
          value: localhost
        - name: TYPEORM_USERNAME
          value: spotify
        - name: TYPEORM_PASSWORD
          value: spotify
        - name: TYPEORM_DATABASE
          value: spotify
        - name: TYPEORM_SYNCHRONIZE
          value: "true"
        - name: TYPEORM_ENTITIES
          value: /app/packages/spotify/build/SpotifyTrackCache.js
        - name: REDIS_URL
          value: redis://localhost
        - name: DEBUG
          value: sactivity,pasteboard:*
        - name: SPOTIFY_COOKIES
          valueFrom:
            secretKeyRef:
              key: cookie
              name: pasteboard-spotify
        image: ericrabil/pasteboard:latest
        imagePullPolicy: IfNotPresent
        name: spotify
      - command:
        - yarn
        - node
        - /app/packages/server/build/index.js
        env:
        - name: DEBUG
          value: '*'
        image: ericrabil/pasteboard:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 9999
          timeoutSeconds: 1
        name: pasteboard
        ports:
        - containerPort: 9999
          name: http
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 9999
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 9999
          timeoutSeconds: 1
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pasteboard-postgres
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: pasteboard
  namespace: pasteboard
spec:
  rules:
  - host: pasteboard.rabil.localtest.me
    http:
      paths:
      - backend:
          service:
            name: pasteboard
            port:
              name: http
        path: /
        pathType: Prefix
